version: "3"
services:
    db:
      image: mysql:5.6
      ports:
        - "3341:3306"
      environment:
        MYSQL_ROOT_PASSWORD: ""
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_DATABASE: 'hh'
        MYSQL_USER: 'gohh'
        MYSQL_PASSWORD: 'gohh'
      container_name: db
      networks:
            - hh_net
    api:
      build:
        context: .
        dockerfile: api/Dockerfile
      ports:
        - "9002:9002"
      volumes:
        - ./api/core:/api/core:cached
      links:
        - db:db
      container_name: api
      networks:
            - hh_net
    socket:
      build:
        context: .
        dockerfile: socket/Dockerfile
      ports:
        - "9001:9001"
      volumes:
        - ./socket/core:/socket/core:cached
      links:
        - api:api
      container_name: socket
      networks:
            - hh_net
    web:
      build:
        context: .
        dockerfile: web/Dockerfile
      ports:
        - "9003:80"
      volumes:
        - ./web/core:/web/core:cached
      links:
        - api:api
      container_name: web
      networks:
            - hh_net
networks:
  hh_net:
